services:
  - type: web
    name: backend-xolk
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ZOHO_EMAIL
        value: noreply@prasatek.lk
      - key: ZOHO_PASSWORD
        value: 49GwqcXhPctJ
      - key: RESEND_API_KEY
        sync: false
