services:
  - type: web
    name: backend-wkpm
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ZOHO_EMAIL
        value: noreply@prasatek.lk
      - key: ZOHO_PASSWORD
        value: 49GwqcXhPctJ
